//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class chromosome
    {
        public chromosome()
        {
            this.geneome_chromosomes = new HashSet<geneome_chromosomes>();
            this.genes = new HashSet<gene>();
        }
    
        public long id { get; set; }
        public string taxonomyid { get; set; }
        public string name { get; set; }
        public Nullable<long> typeid { get; set; }
    
        public virtual chromosome_types chromosome_types { get; set; }
        public virtual ICollection<geneome_chromosomes> geneome_chromosomes { get; set; }
        public virtual ICollection<gene> genes { get; set; }
    }
}
