//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class chromosome_studyparticipants_globals
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public string objkey { get; set; }
        public string value { get; set; }
        public long createdby { get; set; }
        public Nullable<long> modified { get; set; }
        public long created { get; set; }
    }
}
