//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_program_activities
    {
        public long id { get; set; }
        public long csid { get; set; }
        public long parentid { get; set; }
        public long parentmask { get; set; }
        public long programid { get; set; }
        public long gdataid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string pagenum { get; set; }
        public long importance { get; set; }
        public string freqdescinfo { get; set; }
        public string freqtimes { get; set; }
        public string freqsessionsper { get; set; }
        public string freqxpersession { get; set; }
        public string freqxpersessionfreq { get; set; }
        public string freqintensity { get; set; }
        public string tagwords { get; set; }
        public string catchallfield_serialized { get; set; }
        public string depndsonfacilitators { get; set; }
        public string facilitatorsbackground { get; set; }
        public string facilitatorscompensated { get; set; }
        public string facilitatorstrained { get; set; }
        public string facilitatorsmonitors { get; set; }
        public string facilitatorsrole { get; set; }
        public string provides_compensation { get; set; }
        public string provides_compensation_y1 { get; set; }
        public string provides_compensation_y2 { get; set; }
        public string discreteorcontinuous { get; set; }
        public string freqdiscreteconthowlong { get; set; }
        public string freqdiscreteconthowlong_units { get; set; }
        public Nullable<long> freq_startdate { get; set; }
        public Nullable<long> freq_enddate { get; set; }
        public byte flagforreview { get; set; }
        public byte isnew { get; set; }
        public long flagged_roleid { get; set; }
        public Nullable<long> modified { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
        public string DOIsrcfield { get; set; }
        public string nameintervention { get; set; }
    }
}
