//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_messages
    {
        public long id { get; set; }
        public long csid { get; set; }
        public long rootparentid { get; set; }
        public long parentid { get; set; }
        public long gdataid { get; set; }
        public long programid { get; set; }
        public string sectionkey { get; set; }
        public long sectionkeyid { get; set; }
        public Nullable<int> user_roleid { get; set; }
        public long userid { get; set; }
        public string messubject { get; set; }
        public string messagecontent { get; set; }
        public Nullable<long> modified { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
