//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_ns_stem_outcomes
    {
        public long id { get; set; }
        public long csid { get; set; }
        public long parentid { get; set; }
        public Nullable<long> programid { get; set; }
        public long gdataid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string pagenum { get; set; }
        public string tagwords { get; set; }
        public string standardized_outcome { get; set; }
        public string subjective_outcome { get; set; }
        public string assessmenttool { get; set; }
        public string defined_proximity { get; set; }
        public byte flagforreview { get; set; }
        public byte isnew { get; set; }
        public long flagged_roleid { get; set; }
        public Nullable<long> modified { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
        public string intervention_effect { get; set; }
        public string effect_significant { get; set; }
        public string reported_p_value { get; set; }
        public string less_equal_more { get; set; }
        public Nullable<decimal> p_value { get; set; }
        public string outcomepagenumber { get; set; }
        public string measurementtool { get; set; }
        public Nullable<sbyte> used_quantitative { get; set; }
        public string subssample_measured { get; set; }
    }
}
