//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_programs
    {
        public long id { get; set; }
        public long csid { get; set; }
        public long parentid { get; set; }
        public string codeid { get; set; }
        public long gdataid { get; set; }
        public Nullable<long> fileid { get; set; }
        public string dataobjtype { get; set; }
        public string assetlabel { get; set; }
        public string assetmask { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string prevnamedprogram { get; set; }
        public string program_freq { get; set; }
        public Nullable<long> startdate { get; set; }
        public Nullable<long> enddate { get; set; }
        public Nullable<long> durationofprogram { get; set; }
        public string durationunits { get; set; }
        public string pagenum { get; set; }
        public string prog_desc_1 { get; set; }
        public string prog_desc_2 { get; set; }
        public string baseline_desc { get; set; }
        public string programratedescr { get; set; }
        public string programrateactivitiesdescr { get; set; }
        public byte objstatus { get; set; }
        public byte flagforreview { get; set; }
        public byte isnew { get; set; }
        public Nullable<long> modified { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
