//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_list_ordering
    {
        public long gdataid { get; set; }
        public long programid { get; set; }
        public string objkey { get; set; }
        public long objkeyid { get; set; }
        public long orderpos { get; set; }
        public Nullable<int> depth { get; set; }
        public string groupkey { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
