//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_activities_ugs_modifiers
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public long pactid { get; set; }
        public long ugid { get; set; }
        public int ugcid { get; set; }
        public int ugtid { get; set; }
        public int ugmid { get; set; }
        public long usecustommodifier { get; set; }
        public string custommodifiertext { get; set; }
        public long created { get; set; }
        public Nullable<sbyte> importance { get; set; }
        public string sem { get; set; }
    }
}
