//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_backups
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public long programid { get; set; }
        public long userid { get; set; }
        public string rowdata { get; set; }
        public long created { get; set; }
    }
}
