//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding
    {
        public long id { get; set; }
        public long parentid { get; set; }
        public string codinggroupid { get; set; }
        public string codeid { get; set; }
        public long gdataid { get; set; }
        public Nullable<long> fileid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string codingtype { get; set; }
        public byte iscompleted { get; set; }
        public Nullable<long> completeddate { get; set; }
        public byte includeinfinal { get; set; }
        public byte isactive { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
