//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_ctx_study_genes
    {
        public int coding_ctx_study_genes_id { get; set; }
        public Nullable<int> gdataid { get; set; }
        public Nullable<int> coding_program_context_id { get; set; }
        public string percentage { get; set; }
        public Nullable<int> geneid { get; set; }
    }
}
