//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_program_methods_and_dvs
    {
        public long id { get; set; }
        public long csid { get; set; }
        public long parentid { get; set; }
        public long parentmask { get; set; }
        public long programid { get; set; }
        public long gdataid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<byte> used_qualitative { get; set; }
        public Nullable<byte> used_quantitative { get; set; }
        public Nullable<byte> ivs_randassign { get; set; }
        public Nullable<byte> ivs_nonrandassign { get; set; }
        public Nullable<byte> used_crosssect { get; set; }
        public Nullable<byte> used_beforeafter { get; set; }
        public Nullable<byte> used_diffindiff { get; set; }
        public byte used_controlgroup { get; set; }
        public string controlgroup_types { get; set; }
        public string controlgroup_named_program { get; set; }
        public byte flagforreview { get; set; }
        public byte isnew { get; set; }
        public long flagged_roleid { get; set; }
        public Nullable<long> modified { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
        public Nullable<sbyte> reported_effect_size { get; set; }
    }
}
