//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_status_groups
    {
        public long id { get; set; }
        public long parentid { get; set; }
        public int ordernum { get; set; }
        public string sectionkey { get; set; }
        public string sectionkey_name { get; set; }
        public string sectionkey_group { get; set; }
        public string statusdescription { get; set; }
        public string status_icon { get; set; }
        public string status_color { get; set; }
        public long isactive { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
