//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_attributecategory
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public long csid { get; set; }
        public string objkey { get; set; }
        public long objkeyid { get; set; }
        public string attributecategory { get; set; }
        public string attributename { get; set; }
        public string attributevalue { get; set; }
        public string ismajority { get; set; }
        public string description { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
