//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_tags
    {
        public long id { get; set; }
        public string genomeslug { get; set; }
        public long baseobjid { get; set; }
        public string baseobjtype { get; set; }
        public long gdataid { get; set; }
        public Nullable<long> programid { get; set; }
        public string tagwords { get; set; }
        public int specialflag { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
