//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class coding_context_decoded
    {
        public int coding_context_decodedid { get; set; }
        public Nullable<int> gdataid { get; set; }
        public string category { get; set; }
        public string gene { get; set; }
        public Nullable<sbyte> ismajority { get; set; }
    }
}
