//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class exportrequest
    {
        public int exportrequestid { get; set; }
        public Nullable<int> genomeid { get; set; }
        public string requestoremail { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<sbyte> isprocessed { get; set; }
        public Nullable<sbyte> iscompleted { get; set; }
    }
}
