//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileattachment
    {
        public long fileid { get; set; }
        public long gdataid { get; set; }
        public string filename { get; set; }
        public string name { get; set; }
        public string mimetype { get; set; }
        public string fileext { get; set; }
        public byte status { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
