//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class geneomedata_relationships
    {
        public int geneomedata_relationshipsid { get; set; }
        public long gdataid_parent { get; set; }
        public long gdataid_child { get; set; }
        public System.DateTime createddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> studyid { get; set; }
    
        public virtual genomedata genomedata { get; set; }
        public virtual genomedata genomedata1 { get; set; }
        public virtual study study { get; set; }
    }
}
