//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class gene
    {
        public long id { get; set; }
        public string taxonomyid { get; set; }
        public string name { get; set; }
        public Nullable<long> chromosomeid { get; set; }
    
        public virtual chromosome chromosome { get; set; }
    }
}
