//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenomeManagerData : DbContext
    {
        public GenomeManagerData()
            : base("name=GenomeManagerData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<app_settings> app_settings { get; set; }
        public DbSet<chromosome_studyenvironments_globals> chromosome_studyenvironments_globals { get; set; }
        public DbSet<chromosome_studyparticipants_globals> chromosome_studyparticipants_globals { get; set; }
        public DbSet<chromosome_types> chromosome_types { get; set; }
        public DbSet<chromosome> chromosomes { get; set; }
        public DbSet<coding> codings { get; set; }
        public DbSet<coding_activities_ugs> coding_activities_ugs { get; set; }
        public DbSet<coding_activities_ugs_modifiers> coding_activities_ugs_modifiers { get; set; }
        public DbSet<coding_attributecategory> coding_attributecategory { get; set; }
        public DbSet<coding_backups> coding_backups { get; set; }
        public DbSet<coding_ben_study_genes> coding_ben_study_genes { get; set; }
        public DbSet<coding_beneficiary_decoded> coding_beneficiary_decoded { get; set; }
        public DbSet<coding_context_decoded> coding_context_decoded { get; set; }
        public DbSet<coding_ctx_study_genes> coding_ctx_study_genes { get; set; }
        public DbSet<coding_gdataid_outcomeid> coding_gdataid_outcomeid { get; set; }
        public DbSet<coding_groups> coding_groups { get; set; }
        public DbSet<coding_groups_items> coding_groups_items { get; set; }
        public DbSet<coding_messages> coding_messages { get; set; }
        public DbSet<coding_ns_stem_bendef> coding_ns_stem_bendef { get; set; }
        public DbSet<coding_ns_stem_outcomes> coding_ns_stem_outcomes { get; set; }
        public DbSet<coding_peinterrelationship_groups> coding_peinterrelationship_groups { get; set; }
        public DbSet<coding_peinterrelationship_groups_items> coding_peinterrelationship_groups_items { get; set; }
        public DbSet<coding_program_activities> coding_program_activities { get; set; }
        public DbSet<coding_program_characteristics> coding_program_characteristics { get; set; }
        public DbSet<coding_program_comments> coding_program_comments { get; set; }
        public DbSet<coding_program_contexts> coding_program_contexts { get; set; }
        public DbSet<coding_program_curriculum> coding_program_curriculum { get; set; }
        public DbSet<coding_program_effects> coding_program_effects { get; set; }
        public DbSet<coding_program_logistics> coding_program_logistics { get; set; }
        public DbSet<coding_program_methods_and_dvs> coding_program_methods_and_dvs { get; set; }
        public DbSet<coding_programs> coding_programs { get; set; }
        public DbSet<coding_status> coding_status { get; set; }
        public DbSet<coding_status_groups> coding_status_groups { get; set; }
        public DbSet<coding_tags> coding_tags { get; set; }
        public DbSet<effectsimport> effectsimports { get; set; }
        public DbSet<exportrequest> exportrequests { get; set; }
        public DbSet<fileattachment> fileattachments { get; set; }
        public DbSet<geneome_chromosomes> geneome_chromosomes { get; set; }
        public DbSet<geneomedata_relationships> geneomedata_relationships { get; set; }
        public DbSet<gene> genes { get; set; }
        public DbSet<genome_groups> genome_groups { get; set; }
        public DbSet<genomedata> genomedatas { get; set; }
        public DbSet<genomedata_extended_users> genomedata_extended_users { get; set; }
        public DbSet<genomedata_import_history> genomedata_import_history { get; set; }
        public DbSet<genomedata_stem> genomedata_stem { get; set; }
        public DbSet<genomedata_v> genomedata_v { get; set; }
        public DbSet<genome> genomes { get; set; }
        public DbSet<helpcontent> helpcontents { get; set; }
        public DbSet<helpcontent_tracking> helpcontent_tracking { get; set; }
        public DbSet<imprint> imprints { get; set; }
        public DbSet<imprint_task_order> imprint_task_order { get; set; }
        public DbSet<k12genesload> k12genesload { get; set; }
        public DbSet<master_coding_sheet_tracker> master_coding_sheet_tracker { get; set; }
        public DbSet<master_organization> master_organization { get; set; }
        public DbSet<master_outcome_list> master_outcome_list { get; set; }
        public DbSet<master_universalgene_categories> master_universalgene_categories { get; set; }
        public DbSet<master_universalgene_modifiers> master_universalgene_modifiers { get; set; }
        public DbSet<master_universalgene_types> master_universalgene_types { get; set; }
        public DbSet<mf_dashboard_searchhistory> mf_dashboard_searchhistory { get; set; }
        public DbSet<mf_genomedataset_02> mf_genomedataset_02 { get; set; }
        public DbSet<mf_genomedataset_02_summary> mf_genomedataset_02_summary { get; set; }
        public DbSet<mf_genomedataset_top3_02_summary> mf_genomedataset_top3_02_summary { get; set; }
        public DbSet<mf_genomedataset_top5_02> mf_genomedataset_top5_02 { get; set; }
        public DbSet<next_in_queue_excludes> next_in_queue_excludes { get; set; }
        public DbSet<notesketch> notesketches { get; set; }
        public DbSet<notesketch_stem> notesketch_stem { get; set; }
        public DbSet<notesketch_v> notesketch_v { get; set; }
        public DbSet<number> numbers { get; set; }
        public DbSet<overall_study_effectiveness> overall_study_effectiveness { get; set; }
        public DbSet<powerbi_links> powerbi_links { get; set; }
        public DbSet<rating> ratings { get; set; }
        public DbSet<session> sessions { get; set; }
        public DbSet<study> studies { get; set; }
        public DbSet<study_gene_ordering> study_gene_ordering { get; set; }
        public DbSet<subscribe_genome_groups> subscribe_genome_groups { get; set; }
        public DbSet<subscribe_genomes> subscribe_genomes { get; set; }
        public DbSet<subscribe_organization> subscribe_organization { get; set; }
        public DbSet<subscribe_organization_prep> subscribe_organization_prep { get; set; }
        public DbSet<subscribe_outcome_list> subscribe_outcome_list { get; set; }
        public DbSet<tracking> trackings { get; set; }
        public DbSet<user_permissions> user_permissions { get; set; }
        public DbSet<user_pinned> user_pinned { get; set; }
        public DbSet<user_registration_codes> user_registration_codes { get; set; }
        public DbSet<user_roles> user_roles { get; set; }
        public DbSet<user_settings> user_settings { get; set; }
        public DbSet<user_tasks> user_tasks { get; set; }
        public DbSet<usergroup> usergroups { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<users_onefinalreport> users_onefinalreport { get; set; }
        public DbSet<utility_missingfile_report> utility_missingfile_report { get; set; }
        public DbSet<wwc_additionalfields> wwc_additionalfields { get; set; }
        public DbSet<wwc_import_v2> wwc_import_v2 { get; set; }
        public DbSet<wwc_measured> wwc_measured { get; set; }
        public DbSet<wwc_period> wwc_period { get; set; }
        public DbSet<wwceffect> wwceffects { get; set; }
        public DbSet<wwceffects_v2> wwceffects_v2 { get; set; }
        public DbSet<coding_list_ordering> coding_list_ordering { get; set; }
    }
}
