//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class genomedata_stem
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public string institution { get; set; }
        public string associatedwithmeta { get; set; }
        public string subjects { get; set; }
        public string agegroup { get; set; }
        public long created { get; set; }
    }
}
