//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class genomedata_v
    {
        public long id_v { get; set; }
        public string v_action { get; set; }
        public long id { get; set; }
        public string genome { get; set; }
        public long genomeid { get; set; }
        public string documenttitle { get; set; }
        public string searchtermtags { get; set; }
        public string weblink { get; set; }
        public string resourcelead { get; set; }
        public sbyte paywall { get; set; }
        public sbyte accessible { get; set; }
        public string publicprivate { get; set; }
        public string documenttype { get; set; }
        public string othertypedescription { get; set; }
        public string abstractsummary { get; set; }
        public string researchfunderssponsors { get; set; }
        public int monthpublished { get; set; }
        public int yearpublished { get; set; }
        public sbyte previousversions { get; set; }
        public string author1 { get; set; }
        public string author2 { get; set; }
        public string author3 { get; set; }
        public string author4 { get; set; }
        public string author5more { get; set; }
        public string numofpages { get; set; }
        public string journalname { get; set; }
        public string doinumber { get; set; }
        public string volumenum { get; set; }
        public string issuenum { get; set; }
        public string numofcitations { get; set; }
        public string jif { get; set; }
        public string researchmethodology { get; set; }
        public string researchcategory { get; set; }
        public string nameofmfiprograms { get; set; }
        public string countries { get; set; }
        public string relevantoutcomes { get; set; }
        public string subjects { get; set; }
        public string notes { get; set; }
        public string fileattachments { get; set; }
        public byte status { get; set; }
        public long started { get; set; }
        public int rating { get; set; }
        public string ratedby { get; set; }
        public long created { get; set; }
        public long createdby { get; set; }
        public string import_hash { get; set; }
        public Nullable<long> modified { get; set; }
        public Nullable<long> modifiedby { get; set; }
        public long v_created { get; set; }
    }
}
