//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class helpcontent
    {
        public long id { get; set; }
        public string genome { get; set; }
        public string helpkey { get; set; }
        public string helptitle { get; set; }
        public string helptext { get; set; }
        public long viewcount { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
