//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class imprint
    {
        public long imprintid { get; set; }
        public long gdataid { get; set; }
        public string category { get; set; }
        public string feature { get; set; }
        public string answer { get; set; }
        public string group_id { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
