//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class imprint_task_order
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public Nullable<int> ordernum { get; set; }
        public string group_key { get; set; }
        public string group_description { get; set; }
        public Nullable<long> flagged { get; set; }
        public Nullable<long> flaggedby { get; set; }
        public byte status { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
