//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class k12genesload
    {
        public int id { get; set; }
        public Nullable<int> chromosomeid { get; set; }
        public string chromosomename { get; set; }
        public string gene { get; set; }
        public Nullable<int> geneid { get; set; }
    }
}
