//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_universalgene_modifiers
    {
        public int id { get; set; }
        public long ugtid { get; set; }
        public string ugtmname { get; set; }
        public Nullable<int> transferid { get; set; }
    }
}
