//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_universalgene_types
    {
        public long id { get; set; }
        public long genomeid { get; set; }
        public long ugcid { get; set; }
        public string ugtname { get; set; }
        public Nullable<int> transferid { get; set; }
        public Nullable<sbyte> isactive { get; set; }
    }
}
