//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_coding_sheet_tracker
    {
        public int master_coding_sheet_tracker_id { get; set; }
        public Nullable<int> gdataid { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
