//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class mf_genomedataset_top3_02_summary
    {
        public long id { get; set; }
        public Nullable<int> convar { get; set; }
        public string top1 { get; set; }
        public Nullable<int> gene_num_top1 { get; set; }
        public string top2 { get; set; }
        public Nullable<int> gene_num_top2 { get; set; }
        public string top3 { get; set; }
        public Nullable<int> gene_num_top3 { get; set; }
        public string context_name { get; set; }
        public string product_name { get; set; }
        public string outcome_name { get; set; }
        public Nullable<int> context { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> outcome { get; set; }
    }
}
