//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class mf_genomedataset_02_summary
    {
        public long id { get; set; }
        public string gene_name { get; set; }
        public string context_name { get; set; }
        public string product_name { get; set; }
        public string outcome_name { get; set; }
        public Nullable<int> gene { get; set; }
        public Nullable<int> context { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> outcome { get; set; }
        public string error_code { get; set; }
        public Nullable<float> prior_beta { get; set; }
        public Nullable<float> prior_se { get; set; }
        public Nullable<float> prior_lci { get; set; }
        public Nullable<float> prior_uci { get; set; }
        public Nullable<int> post_obs { get; set; }
        public Nullable<int> post_pos { get; set; }
        public Nullable<float> prior_obs { get; set; }
        public Nullable<float> perprior_pos { get; set; }
        public Nullable<decimal> post_beta { get; set; }
        public Nullable<decimal> post_se { get; set; }
        public Nullable<float> post_lci { get; set; }
        public Nullable<float> post_uci { get; set; }
        public string diagnostgraph_name { get; set; }
        public string updategraph_name { get; set; }
        public string genedefinition { get; set; }
        public string additionalinfo { get; set; }
        public string numobs { get; set; }
        public string tabobs { get; set; }
        public string group_attribute { get; set; }
        public Nullable<int> dc_none { get; set; }
        public Nullable<int> dc_noncomp_vh { get; set; }
        public Nullable<int> dc_noncomp_h { get; set; }
        public Nullable<int> dc_noncomp_m { get; set; }
        public Nullable<int> dc_noncomp_l { get; set; }
        public Nullable<int> dc_rct_vh { get; set; }
        public Nullable<int> dc_rct_h { get; set; }
        public Nullable<int> dc_rct_m { get; set; }
        public Nullable<int> dc_rct_l { get; set; }
        public Nullable<int> dc_grt_vh { get; set; }
        public Nullable<int> dc_grt_h { get; set; }
        public Nullable<int> dc_grt_m { get; set; }
        public Nullable<int> dc_grt_l { get; set; }
        public Nullable<int> dc_cos_vh { get; set; }
        public Nullable<int> dc_cos_h { get; set; }
        public Nullable<int> dc_cos_m { get; set; }
        public Nullable<int> dc_cos_l { get; set; }
        public Nullable<int> dc_uos_vh { get; set; }
        public Nullable<int> dc_uos_h { get; set; }
        public Nullable<int> dc_uos_m { get; set; }
        public Nullable<int> dc_uos_l { get; set; }
        public Nullable<int> dc_noncomp_vl { get; set; }
        public Nullable<int> dc_rct_vl { get; set; }
        public Nullable<int> dc_grt_vl { get; set; }
        public Nullable<int> dc_cos_vl { get; set; }
        public Nullable<int> dc_uos_vl { get; set; }
        public Nullable<int> reg_la { get; set; }
        public Nullable<int> reg_af { get; set; }
        public Nullable<int> reg_as { get; set; }
        public Nullable<int> reg_ee { get; set; }
        public Nullable<int> reg_me { get; set; }
        public Nullable<int> reg_mr { get; set; }
        public Nullable<int> reg_ww { get; set; }
        public Nullable<int> reg_un { get; set; }
        public Nullable<int> convar { get; set; }
        public Nullable<int> topfives { get; set; }
        public Nullable<decimal> probtop5 { get; set; }
    }
}
