//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmx_map_data
    {
        public long id { get; set; }
        public string object_id { get; set; }
        public string ein { get; set; }
        public string OrgName { get; set; }
        public string ProgramName { get; set; }
        public string ProgramDescription { get; set; }
        public Nullable<long> Adjusted { get; set; }
        public long Outcomes { get; set; }
        public long CPO { get; set; }
        public string Description { get; set; }
        public Nullable<long> Budget { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string UniversalOutcomeId { get; set; }
        public Nullable<int> OutcomeId { get; set; }
        public string OutcomeName { get; set; }
        public string ImpactArea { get; set; }
        public string Genome { get; set; }
        public string OutcomeDescription { get; set; }
        public Nullable<long> AverageAcheived { get; set; }
        public Nullable<long> MinAcheived { get; set; }
        public Nullable<long> MaxAcheived { get; set; }
        public Nullable<long> AverageCPO { get; set; }
        public Nullable<long> MinCPO { get; set; }
        public Nullable<long> MaxCPO { get; set; }
        public Nullable<long> AlgoliaObjectId { get; set; }
    }
}
