//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class notesketch_stem
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public string stemoutcomes { get; set; }
        public string stemoutcomes_b { get; set; }
        public string stemoutcomes_c { get; set; }
        public string beneficiary { get; set; }
        public string schoolteacherdef { get; set; }
        public string programcurriculum { get; set; }
        public string programactivitiesfocus { get; set; }
        public string programlogistics { get; set; }
        public string programintensity { get; set; }
        public string programpersistance { get; set; }
        public string organizationdef { get; set; }
        public string notescommentsmore { get; set; }
        public int ns_status { get; set; }
        public int status { get; set; }
        public long modified { get; set; }
        public long modifiedby { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
