//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class notesketch_v
    {
        public long nsid_v { get; set; }
        public string v_action { get; set; }
        public long id { get; set; }
        public long gdataid { get; set; }
        public string microfinanceoutcomes { get; set; }
        public string clientbeneficiary { get; set; }
        public string generalpopbeneficiary { get; set; }
        public string geography { get; set; }
        public string budget { get; set; }
        public string mfidefinition { get; set; }
        public string partnerorganizations { get; set; }
        public string mfiproductrelationship { get; set; }
        public string barrierstooutcomes { get; set; }
        public string otherkeyissues { get; set; }
        public string financialproductsservices { get; set; }
        public string nonfinancialproducsservices { get; set; }
        public string surveyinfo { get; set; }
        public string programpersistence { get; set; }
        public string organizationalidentity { get; set; }
        public string notes { get; set; }
        public string threatstovalidity { get; set; }
        public string treatmentfactors { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
        public long modified { get; set; }
        public Nullable<long> modifiedby { get; set; }
        public int ns_status { get; set; }
        public byte status { get; set; }
        public long v_created { get; set; }
    }
}
