//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntee_outcomes_lookup
    {
        public int id { get; set; }
        public Nullable<int> EIN { get; set; }
        public string CITY { get; set; }
        public string EXPS { get; set; }
        public string NAME { get; set; }
        public string NTEE1 { get; set; }
        public string NTEECC_Cleaned { get; set; }
        public string NTMAJ10 { get; set; }
        public string NTMAJ12 { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> outcomeid { get; set; }
    }
}
