//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class overall_study_effectiveness
    {
        public int id { get; set; }
        public int gdataid { get; set; }
        public Nullable<int> pos_effect { get; set; }
        public Nullable<int> effectid { get; set; }
    }
}
