//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class powerbi_links
    {
        public int group_code { get; set; }
        public string url { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<sbyte> active { get; set; }
        public string title { get; set; }
        public int id { get; set; }
        public Nullable<sbyte> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<sbyte> type { get; set; }
    
        public virtual user user { get; set; }
    }
}
