//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public long ratingid { get; set; }
        public long userid { get; set; }
        public Nullable<int> userrating { get; set; }
        public string userrating_value { get; set; }
        public string ratingtype { get; set; }
        public Nullable<long> gdataid { get; set; }
        public Nullable<long> nsid { get; set; }
        public Nullable<long> fileid { get; set; }
        public string ratinghistory { get; set; }
        public Nullable<long> modified { get; set; }
        public long created { get; set; }
    }
}
