//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public long id { get; set; }
        public string ipaddress { get; set; }
        public string sessionid { get; set; }
        public long userid { get; set; }
        public string uri { get; set; }
        public long created { get; set; }
    }
}
