//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class study
    {
        public study()
        {
            this.geneomedata_relationships = new HashSet<geneomedata_relationships>();
        }
    
        public int studyid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> modifiedby { get; set; }
    
        public virtual ICollection<geneomedata_relationships> geneomedata_relationships { get; set; }
    }
}
