//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscribe_genomes
    {
        public long id { get; set; }
        public long groupid { get; set; }
        public string name { get; set; }
        public string genomeslug { get; set; }
        public string description { get; set; }
        public int listorder { get; set; }
        public string iconhtml { get; set; }
        public string iconclass { get; set; }
        public string tmpl_bibview { get; set; }
        public string tmpl_bibnew { get; set; }
        public string tmpl_bibedit { get; set; }
        public int status { get; set; }
        public float codingstatus { get; set; }
        public float presentationstatus { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
