//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscribe_organization
    {
        public long id { get; set; }
        public long genomeid { get; set; }
        public string OrganizationName { get; set; }
        public long outcomeid { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
