//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxonomy_dbEntities : DbContext
    {
        public taxonomy_dbEntities()
            : base("name=taxonomy_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<v_activeimpactareas> v_activeimpactareas { get; set; }
        public DbSet<v_activeoutcomes> v_activeoutcomes { get; set; }
        public DbSet<v_genes> v_genes { get; set; }
        public DbSet<v_latestbenchmarks> v_latestbenchmarks { get; set; }
    }
}
