//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        public long trackingid { get; set; }
        public long userid { get; set; }
        public string sessionid { get; set; }
        public string ipaddress { get; set; }
        public string url { get; set; }
        public string url_previous { get; set; }
        public string postdata { get; set; }
        public string trackingkey { get; set; }
        public string task { get; set; }
        public long created { get; set; }
    }
}
