//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_registration_codes
    {
        public long id { get; set; }
        public string code { get; set; }
        public string redirect { get; set; }
        public long usergroupid { get; set; }
        public long userroleid { get; set; }
        public byte status { get; set; }
        public long created { get; set; }
    }
}
