//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_pinned
    {
        public long pinid { get; set; }
        public long userid { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public Nullable<long> gdataid { get; set; }
        public Nullable<long> notesketchid { get; set; }
        public Nullable<long> fileid { get; set; }
        public string pintype { get; set; }
        public long status { get; set; }
        public long created { get; set; }
    }
}
