//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permissions
    {
        public long id { get; set; }
        public int permid { get; set; }
        public long permidvalue { get; set; }
        public string name { get; set; }
        public Nullable<long> permgroupid { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
