//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tasks
    {
        public long utaskid { get; set; }
        public long parent_utaskid { get; set; }
        public Nullable<long> gdataid { get; set; }
        public Nullable<long> programid { get; set; }
        public string sectionkey { get; set; }
        public string sectionkey_value { get; set; }
        public string xrefvarvalue { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public string token { get; set; }
        public string description { get; set; }
        public string message { get; set; }
        public Nullable<long> duedate { get; set; }
        public long completed { get; set; }
        public string completed_notes { get; set; }
        public Nullable<long> completed_linked_utaskid { get; set; }
        public byte status { get; set; }
        public long createdby { get; set; }
        public long created { get; set; }
    }
}
