//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class utility_missingfile_report
    {
        public long id { get; set; }
        public long gdataid { get; set; }
        public Nullable<long> fileid { get; set; }
        public string report_typeslug { get; set; }
        public string filepath { get; set; }
        public string displayname { get; set; }
        public long userid { get; set; }
        public string fullname { get; set; }
        public long createdby { get; set; }
        public long hits { get; set; }
        public Nullable<long> modified { get; set; }
        public long created { get; set; }
    }
}
