//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_activeimpactareas
    {
        public int impactareaid { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<sbyte> isactive { get; set; }
    }
}
