//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_activeoutcomes
    {
        public int outcomeid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string definition { get; set; }
        public Nullable<int> impactareaid { get; set; }
        public Nullable<int> genomeid { get; set; }
        public string universaloutcomeid { get; set; }
        public string symbol { get; set; }
        public string impactlanguage { get; set; }
        public Nullable<sbyte> isuniversal { get; set; }
        public Nullable<sbyte> isactive { get; set; }
        public string genomename { get; set; }
        public string impactarea { get; set; }
        public string beneficiarytypename { get; set; }
    }
}
