//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_genes
    {
        public int geneid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int chromosomeid { get; set; }
        public string chromosomename { get; set; }
        public string chromosomecode { get; set; }
        public int genomeid { get; set; }
        public string genome { get; set; }
        public int impactareaid { get; set; }
        public string impactarea { get; set; }
        public string genecode { get; set; }
    }
}
