//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwc_import_v2
    {
        public int id { get; set; }
        public Nullable<int> GdataID { get; set; }
        public Nullable<int> effects_id { get; set; }
        public Nullable<int> f_FindingID { get; set; }
        public string s_Citation { get; set; }
        public string s_Intervention_Name { get; set; }
        public string s_Study_Design { get; set; }
        public Nullable<int> s_StudyID { get; set; }
        public Nullable<int> f_FindingID__0_ { get; set; }
        public Nullable<int> f_InterventionID { get; set; }
        public string f_Intervention_Name { get; set; }
        public string f_Comparison { get; set; }
        public Nullable<int> f_Outcome_MeasureID { get; set; }
        public string f_Outcome_Measure { get; set; }
        public string f_Period { get; set; }
        public string f_Sample_Description { get; set; }
        public string f_Is_Subgroup { get; set; }
        public Nullable<int> f_Outcome_Sample_Size { get; set; }
        public Nullable<int> f_Outcome_Intervention_SS { get; set; }
        public Nullable<int> f_Outcome_Comparison_SS { get; set; }
        public Nullable<int> f_Intervention_Clusters_SS { get; set; }
        public Nullable<int> f_Comparison_Clusters_SS { get; set; }
        public string f_Intervention_Mean { get; set; }
        public string f_Comparison_Mean { get; set; }
        public string f_Intervention_Standard_Deviation { get; set; }
        public string f_Comparison_Standard_Deviation { get; set; }
        public string f_Effect_Size_Study { get; set; }
        public Nullable<double> f_Effect_Size_WWC { get; set; }
        public Nullable<int> f_Improvement_Index { get; set; }
        public string f_p_Value_Study { get; set; }
        public Nullable<double> f_p_Value_WWC { get; set; }
        public string f_ICC { get; set; }
        public string f_Clusters_Total { get; set; }
        public string f_Is_Statistically_Significant { get; set; }
        public string f_Finding_Rating { get; set; }
        public string f_ESSA_Rating { get; set; }
        public string f_L1_Unit_of_Analysis { get; set; }
    }
}
