//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwc_additionalfields
    {
        public int id { get; set; }
        public Nullable<int> GdataID { get; set; }
        public string s_Study_Design { get; set; }
        public Nullable<int> s_StudyID { get; set; }
        public string f_Intervention_Name { get; set; }
        public string f_Comparison { get; set; }
        public string f_Outcome_Measure { get; set; }
        public string f_Is_Subgroup { get; set; }
        public Nullable<int> f_Outcome_Sample_Size { get; set; }
        public string f_Effect_Size_Study { get; set; }
        public string f_Effect_Size_WWC { get; set; }
        public string f_Improvement_Index { get; set; }
        public string f_p_Value_WWC { get; set; }
        public string f_ICC { get; set; }
        public string f_Finding_Rating { get; set; }
        public string f_ESSA_Rating { get; set; }
        public string f_L1_Unit_of_Analysis { get; set; }
        public Nullable<int> findingid { get; set; }
    }
}
