//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.AlgoliaLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwceffect
    {
        public int id { get; set; }
        public Nullable<int> gdataid { get; set; }
        public string s_Citation { get; set; }
        public string outcomemeasured { get; set; }
        public string f_Sample_Description { get; set; }
        public Nullable<int> f_Outcome_Intervention_SS { get; set; }
        public Nullable<int> f_Outcome_Comparison_SS { get; set; }
        public string f_Intervention_Clusters_SS { get; set; }
        public string f_Comparison_Clusters_SS { get; set; }
        public Nullable<double> f_Intervention_Mean { get; set; }
        public Nullable<double> f_Comparison_Mean { get; set; }
        public Nullable<double> f_Intervention_Standard_Deviation { get; set; }
        public Nullable<double> f_Comparison_Standard_Deviation { get; set; }
        public string f_p_Value_Study { get; set; }
        public string f_Clusters_Total { get; set; }
        public string f_period { get; set; }
    }
}
